name: Build and Push the Docker container
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
     - name: Checkout
       uses: actions/checkout@v1
       with:
         fetch-depth: 1
     - name: Build docker image
       uses: zenato/docker-action@master
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
         repository: alpine-pandoc
         tag: latest
